import eslint from "@eslint/js";
import tseslint from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";

export default [
  { ignores: ["**/node_modules/**", "**/dist/**", "**/src-tauri/**"] },
  eslint.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 2020,
        sourceType: "module",
        ecmaFeatures: { jsx: true },
      },
      globals: {
        window: "readonly",
        document: "readonly",
        fetch: "readonly",
        RequestInit: "readonly",
        Response: "readonly",
        TextDecoder: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        console: "readonly",
        require: "readonly",
        module: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        KeyboardEvent: "readonly",
        Blob: "readonly",
        URL: "readonly",
        navigator: "readonly",
        Request: "readonly",
        Headers: "readonly",
        ReadableStream: "readonly",
        ReadableStreamDefaultController: "readonly",
        DOMException: "readonly",
        AbortSignal: "readonly",
        AbortController: "readonly",
        MutationObserver: "readonly",
        localStorage: "readonly",
        process: "readonly",
        HTMLElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLSpanElement: "readonly",
        HTMLButtonElement: "readonly",
        SVGSVGElement: "readonly",
        MouseEvent: "readonly",
        HeadersInit: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        alert: "readonly",
        confirm: "readonly",
        HTMLInputElement: "readonly",
        HTMLSelectElement: "readonly",
        Node: "readonly",
        File: "readonly",
        FileList: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        EventSource: "readonly",
        React: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
      react,
      "react-hooks": reactHooks,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-require-imports": "off",
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
    },
  },
];
