"""Tool registry: defines tool visibility tiers for the MCP server.

Phase A (2026-07-01): 17 CORE tools + escape hatch (memory_advanced).
Phase B (2026-07-15): +1 CORE tool (memory_record_ctr_feedback) for CTR feedback.

CORE_TOOLS:    25 tools total — all visible directly on the MCP surface.
                Everything else is accessible via memory_maintenance(operation="...")
                or memory_advanced(operation="...").
ADMIN_TOOLS:    Legacy tools callable via memory_maintenance / memory_advanced.
DEPRECATED:     Tools superseded by verbs (also present in ADMIN_TOOLS;
                listed here for audit/logging only).
"""

CORE_TOOLS = [
    "memory_search",
    "memory_save",
    "memory_delete",
    "memory_recall",
    "memory_note",
    "memory_learn",
    "memory_audit",
    "memory_organize",
    "memory_share",
    "memory_graph",
    "memory_profile",
    "memory_session_start",
    "memory_session_end",
    "memory_list_revisions",
    "memory_advanced",
    "memory_review_beliefs",
    "memory_curate_autosave",
    "memory_health_check",
    "memory_system_health",
    "memory_recall_context",
    "memory_record_ctr_feedback",
    # Agent-facing self-editing surface (promoted from ADMIN — see AGENTS.md
    # "Self-editing" section). Auto skill extraction already runs on every
    # save; these let agents trigger/inspect skill compile + extraction
    # directly instead of going through the memory_maintenance router.
    "memory_list_skills",
    "memory_extract_skills",
    "memory_compile_skill",
    "memory_coordinate",
]

ADMIN_TOOLS = [
    "memory_graph_insights",
    "memory_graph_evolution",
    "memory_maintenance",
    "memory_adaptive_retention",
    "memory_arc_stats",
    "memory_audit_query",
    "memory_auto_save_hook",
    "memory_auto_save_status",
    "memory_auto_save_daemon_metrics",
    "memory_auto_summarize",
    "memory_backfill_all",
    "memory_check_concept_drift",
    "memory_check_integrity",
    "memory_compact",
    "memory_consolidate",
    "memory_daily_digest",
    "memory_detect_contradictions",
    "memory_facts_list",
    "memory_facts_stats",
    "memory_gdpr_erase",
    "memory_graph_stats",
    "memory_pinned_decay_check",
    "memory_profile_stats",
    "memory_purge_expired",
    "memory_purge_auto_saves",
    "memory_quality_filter",
    "memory_quality_stats",
    "memory_list_drift_alarms",
    "memory_reinforce",
    "memory_retention_stats",
    "memory_review_schedule",

    "memory_restore",
    "memory_rebuild",
    "memory_supersede",
    "memory_shared_import",
    "memory_shared_list",
    "memory_shared_stats",
    "memory_strip_provenance",
    "memory_summarize",
    "memory_summarization_stats",
    "memory_trash",
    "memory_crdt_sync",
    "memory_crdt_status",
    "memory_okf_export",
    "memory_okf_import",
    "memory_heartbeat",
    "memory_tier_stats",
    "memory_run_tier_migration",
    "memory_check_embedding_model",
    "memory_incremental_update",
    "memory_dedup",
    "memory_session_admin_stats",
    "memory_llm_unload",
    "memory_ingest",
    "memory_dashboard",
    "memory_metrics_server",
    "memory_admin_policy_hash",
    "memory_agent_init",
    "memory_agent_clear",
    "memory_agent_list",
    "memory_arc_reset",
    "memory_sdk_demo",
    "memory_auto_share",
    "memory_graph_shortest_path",
    "memory_graph_traverse",
    "memory_circuit_breaker_status",
    "memory_temporal_contradictions",
    "memory_temporal_query",
    "memory_compliance_check",
    "memory_semantic_search",
    "memory_facts_search",
    "memory_graph_search",
    "memory_recall_stats",
    "memory_thread_context",
    "memory_list_threads",
    "memory_resolve_thread",
    "memory_user_profile",
    "memory_check_contradictions",
    "memory_scan_injection",
    "memory_profile_access",
    "memory_rewrite_links",
    "memory_list_federated_skills",
    "memory_resolve_contradiction",
    "memory_background_task_status",
    "memory_pipeline_coverage",
    "memory_login_url",
    "memory_callback",
    "memory_whoami",
    "memory_rotate_key",
    "memory_sso_sync_metadata",
    "memory_sso_idp_list",
    "memory_sso_idp_add",
]

DEPRECATED = [
    "memory_incremental_update",
    "memory_check_embedding_model",
    "memory_run_tier_migration",
]
