"""Tool registry: defines tool visibility tiers for the MCP server.

Phase A (2026-07-01): 14 verbs + 1 escape hatch (memory_advanced).

CORE_TOOLS:    15 tools total — all visible directly on the MCP surface.
                Everything else is accessible via memory_maintenance(operation="...")
                or memory_advanced(operation="...").
ADMIN_TOOLS:    Legacy tools callable via memory_maintenance / memory_advanced.
DEPRECATED:     Tools superseded by verbs (also present in ADMIN_TOOLS;
                listed here for audit/logging only).
"""

CORE_TOOLS = [
    "memory_search",
    "memory_save",
    "memory_delete",
    "memory_recall",
    "memory_note",
    "memory_learn",
    "memory_audit",
    "memory_organize",
    "memory_share",
    "memory_graph",
    "memory_profile",
    "memory_session_start",
    "memory_advanced",
    "memory_review_beliefs",
    "memory_curate_autosave",
]

ADMIN_TOOLS = [
    "memory_graph_insights",
    "memory_graph_evolution",
    "memory_maintenance",
    "memory_adaptive_retention",
    "memory_arc_stats",
    "memory_audit_query",
    "memory_auto_save_hook",
    "memory_auto_save_status",
    "memory_auto_save_daemon_metrics",
    "memory_auto_summarize",
    "memory_backfill_all",
    "memory_check_concept_drift",
    "memory_check_integrity",
    "memory_compact",
    "memory_consolidate",
    "memory_compile_skill",
    "memory_daily_digest",
    "memory_detect_contradictions",
    "memory_facts_list",
    "memory_facts_stats",
    "memory_graph_stats",
    "memory_pinned_decay_check",
    "memory_profile_stats",
    "memory_purge_expired",
    "memory_purge_auto_saves",
    "memory_quality_filter",
    "memory_quality_stats",
    "memory_record_ctr_feedback",
    "memory_list_drift_alarms",
    "memory_reinforce",
    "memory_retention_stats",
    "memory_review_schedule",

    "memory_restore",
    "memory_rebuild",
    "memory_supersede",
    "memory_health_check",
    "memory_shared_import",
    "memory_shared_list",
    "memory_shared_stats",
    "memory_strip_provenance",
    "memory_summarize",
    "memory_summarization_stats",
    "memory_trash",
    "memory_crdt_sync",
    "memory_crdt_status",
    "memory_okf_export",
    "memory_okf_import",
    "memory_heartbeat",
    "memory_tier_stats",
    "memory_run_tier_migration",
    "memory_check_embedding_model",
    "memory_incremental_update",
    "memory_duplicates",
    "memory_merge_suggestions",
    "memory_llm_unload",
    "memory_ingest_file",
    "memory_ingest_url",
    "memory_dashboard",
    "memory_metrics_server",
    "memory_agent_init",
    "memory_agent_clear",
    "memory_agent_list",
    "memory_arc_reset",
    "memory_extract_skills",
    "memory_list_skills",
    "memory_sdk_demo",
    "memory_auto_share",
    "memory_graph_shortest_path",
    "memory_graph_traverse",
    "memory_circuit_breaker_status",
    "memory_recall_status",
    "memory_recall_trace",
    "memory_temporal_contradictions",
    "memory_temporal_query",
    "memory_compliance_check",
    "memory_semantic_search",
    "memory_facts_search",
    "memory_graph_search",
    "memory_recall_context",
    "memory_thread_context",
    "memory_list_threads",
    "memory_resolve_thread",
    "memory_user_profile",
    "memory_check_contradictions",
    "memory_scan_injection",
    "memory_profile_access",
    "memory_rewrite_links",
]

DEPRECATED = [
    "memory_incremental_update",
    "memory_check_embedding_model",
    "memory_run_tier_migration",
]
