-- 057 down: remove the search-reranker foundation tables.
--
-- Drops the three tables created by 057_search_reranker_foundation.sql.
-- The memory_temporal_priors seed rows inserted by the up-migration vanish
-- with the table drop — this is acceptable for a down migration: the priors
-- are static defaults regenerated by the up-migration on any future
-- re-apply, so no operator-authored data is lost. (No FK references these
-- tables yet; this is foundational schema.)

DROP TABLE IF EXISTS memory_search_interaction;
DROP TABLE IF EXISTS memory_query_type_stats;
DROP TABLE IF EXISTS memory_temporal_priors;
