# /usr/bin/env python3
"""Shared helpers for the auto-gen reference doc scripts.

Each generator produces an *automated* core (tool list, schema tables, config
keys) and must PRESERVE hand-written manual sections that live in the target
file. We wrap the generated core between two markers:

    <!-- AUTO-GEN-START -->
    <generated core content>
    <!-- AUTO-GEN-END -->

    <preserved manual content>

On regeneration we read the existing file: everything OUTSIDE the markers is
treated as manual content and re-appended after the freshly generated core.

On the very first run (no markers yet) we fall back to locating known manual
section headers so the manual content that a previous agent hand-added is not
lost.
"""
from __future__ import annotations

from typing import List

START = "<!-- AUTO-GEN-START -->"
END = "<!-- AUTO-GEN-END -->"

_GENERATED_FOOTER_MARKER = "This file is generated by"

# Manual section headers we recognise. The EARLIEST one present in a
# marker-less file marks where the hand-written content begins.
MANUAL_HEADERS: List[str] = [
    "## Overview",
    "## Quick Reference",
    "## Error Handling",
    "## Troubleshooting",
    "## Examples",
    "## Related",
    "## Manual Supplement",
    "## Priority Order",
    "## Configuration Examples",
    "## Further Reading",
    "## Core Tables",
    "## Multi-Agent Tables",
    "## Knowledge Graph Tables",
    "## Audit",
    "## Operational Tables",
]


def extract_manual(existing: str, legacy_starts: List[str] | None = None) -> str:
    """Extract preserved manual content from an existing target file.

    If the file already carries AUTO-GEN markers, manual content is everything
    outside them. Otherwise (first run) we fall back to locating the earliest
    recognised manual section header and stripping the trailing generated
    footer.
    """
    if START in existing and END in existing:
        before, rest = existing.split(START, 1)
        _, after = rest.split(END, 1)
        return (before + after).strip()

    # First run: locate the earliest manual section header.
    starts = legacy_starts if legacy_starts else MANUAL_HEADERS
    start_idx: int | None = None
    for h in starts:
        i = existing.find(h)
        if i != -1 and (start_idx is None or i < start_idx):
            start_idx = i
    if start_idx is None:
        return ""
    return _strip_trailing_footer(existing[start_idx:])


def _strip_trailing_footer(text: str) -> str:
    """Remove a trailing ``---`` + ``*This file is generated by ...*`` footer."""
    lines = text.rstrip().splitlines()
    while lines and lines[-1].strip() == "":
        lines.pop()
    while lines and lines[-1].lstrip().startswith("*" + _GENERATED_FOOTER_MARKER):
        lines.pop()
        while lines and lines[-1].strip() in ("", "---"):
            lines.pop()
    return "\n".join(lines).rstrip()


def assemble(core: str, manual: str) -> str:
    """Combine generated core + preserved manual into the final document."""
    core = core.rstrip("\n")
    manual = manual.strip("\n")
    parts = [START, core, END]
    if manual:
        parts.append("")
        parts.append(manual)
    parts.append("")
    return "\n".join(parts)


def strip_markers(text: str) -> str:
    """Return only the generated core (everything between the markers)."""
    if START in text and END in text:
        _, rest = text.split(START, 1)
        core, _ = rest.split(END, 1)
        return core.strip("\n")
    return text.strip("\n")
