#!/usr/bin/env python3
"""Config Flag Audit & Inventory Generator for Agentic Memory.

Introspects config flags and generates a markdown table with:
- Feature Flag Name
- TOML Key / Section
- Environment Override Var
- Default Value
- Recommended Value for Fresh Installs
- Status
"""

from __future__ import annotations

import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from infra.config import get_config, get_feature_flags


def generate_inventory() -> str:
    flags = get_feature_flags()
    lines = [
        "# Agentic Memory Configuration Flag Inventory",
        "",
        "This document is auto-generated by `scripts/audit_config_flags.py`.",
        "",
        "| Flag Name | Env Override | TOML Key | Current Value | Default | Status |",
        "|---|---|---|---|---|---|",
    ]

    for flag_name, meta in sorted(flags.items()):
        val = meta.get("value")
        env_var = meta.get("env_var", "—")
        toml_key = meta.get("toml_key", "—")
        default_val = meta.get("default", "—")
        status = "Safe / Active" if val else "Disabled / Off"
        if flag_name == "session_memory" and not val:
            status = "⚠️ Unsafe Off (Should be True)"
        lines.append(f"| `{flag_name}` | `{env_var}` | `{toml_key}` | `{val}` | `{default_val}` | {status} |")

    return "\n".join(lines)


def main() -> int:
    inventory = generate_inventory()
    print(inventory)
    out_file = _REPO_ROOT / "docs" / "config-flag-inventory.md"
    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text(inventory)
    print(f"\n[+] Wrote flag inventory to {out_file}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
