#!/usr/bin/env python3
"""Unified documentation drift checker.

Verifies three docs stay in sync with live code:
  1. docs/architecture.md — regenerated by scripts/generate_architecture_md.py
  2. AGENTS.md AUTO-GEN sections — live counts from tool_registry.py, migration_runner.py
  3. docs/MCP_SURFACE.md tool counts — must match tool_registry.py

Usage: python scripts/doc_drift_check.py
Exit: 0 if all match, 1 if any drift detected.
"""
from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Shared: parse live code for ground-truth counts
# ---------------------------------------------------------------------------


def _parse_tool_registry() -> dict[str, int]:
    text = (REPO / "tool_registry.py").read_text(encoding="utf-8")
    tree = ast.parse(text)
    core = admin = deprecated = 0
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        target = node.targets[0] if node.targets else None
        if not isinstance(target, ast.Name) or not isinstance(node.value, ast.List):
            continue
        if target.id == "CORE_TOOLS":
            core = len(node.value.elts)
        elif target.id == "ADMIN_TOOLS":
            admin = len(node.value.elts)
        elif target.id == "DEPRECATED":
            deprecated = len(node.value.elts)
    return {"core": core, "admin": admin, "deprecated": deprecated, "total": core + admin + deprecated}


def _parse_schema_version() -> int:
    text = (REPO / "infra" / "migration_runner.py").read_text(encoding="utf-8")
    m = re.search(r"SCHEMA_VERSION\s*=\s*(\d+)", text)
    return int(m.group(1)) if m else 0


def _count_migrations() -> int:
    return len(list((REPO / "migrations").glob("*.down.sql")))


def _count_test_files() -> int:
    return len(list((REPO / "eval").glob("test_*.py")))


def _count_test_functions() -> int:
    count = 0
    for f in (REPO / "eval").glob("test_*.py"):
        try:
            for line in f.read_text(encoding="utf-8").splitlines():
                if re.match(r"\s+def test_", line):
                    count += 1
        except OSError:
            pass
    return count


def _count_hooks() -> int:
    return len([f for f in (REPO / "hooks").glob("*.py") if not f.stem.startswith("_")])


def _count_cron_scripts() -> int:
    """Count scheduled cron jobs from the canonical ``JOBS`` registry.

    Uses ``cron/jobs.py`` ``JOBS`` (the single source of truth for scheduled
    jobs) rather than globbing ``cron/*.py``, which also matches helper/
    utility modules that are not scheduled jobs.  Consistent with
    ``agents_md_generator.py`` and ``gen_readme_badges.py``.
    """
    try:
        import importlib.util

        spec = importlib.util.spec_from_file_location("cron_jobs", REPO / "cron" / "jobs.py")
        if spec is None or spec.loader is None:
            return len([f for f in (REPO / "cron").glob("*.py") if f.is_file()])
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return len(getattr(mod, "JOBS", {}))
    except Exception:
        return len([f for f in (REPO / "cron").glob("*.py") if f.is_file()])


def _count_mcp_modules() -> int:
    return len(list(REPO.glob("mcp_*.py")))


# ---------------------------------------------------------------------------
# Check 1: architecture.md via generate script
# ---------------------------------------------------------------------------


def check_architecture_md() -> list[str]:
    errors: list[str] = []
    generator = REPO / "scripts" / "generate_architecture_md.py"
    if not generator.exists():
        errors.append("scripts/generate_architecture_md.py not found")
        return errors

    import subprocess
    result = subprocess.run(
        [sys.executable, str(generator)],
        cwd=str(REPO),
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        errors.append(f"Generator failed: {result.stderr.strip()}")
        return errors

    generated = (REPO / "docs" / "architecture.md").read_text(encoding="utf-8")
    checked_in = (REPO / "docs" / "architecture.md").read_text(encoding="utf-8")
    if generated != checked_in:
        errors.append("docs/architecture.md has drifted — run: python scripts/generate_architecture_md.py")
    return errors


# ---------------------------------------------------------------------------
# Check 2: AGENTS.md AUTO-GEN sections
# ---------------------------------------------------------------------------


def _parse_agents_md_auto_gen(text: str) -> dict[str, str]:
    """Extract AUTO-GEN section contents keyed by their key attribute."""
    pattern = re.compile(
        r"<!--AUTO-GEN:START key=\"(\w+)\"-->\n(.*?)\n<!--AUTO-GEN:END key=\"\1\"-->",
        re.DOTALL,
    )
    return {m.group(1): m.group(2) for m in pattern.finditer(text)}


def check_agents_md() -> list[str]:
    errors: list[str] = []
    agents_md = REPO / "AGENTS.md"
    if not agents_md.exists():
        errors.append("AGENTS.md not found")
        return errors

    text = agents_md.read_text(encoding="utf-8")
    sections = _parse_agents_md_auto_gen(text)
    if not sections:
        errors.append("No AUTO-GEN sections found in AGENTS.md")
        return errors

    tools = _parse_tool_registry()
    schema_version = _parse_schema_version()
    migrations = _count_migrations()
    test_files = _count_test_files()
    test_funcs = _count_test_functions()
    hooks = _count_hooks()
    cron = _count_cron_scripts()
    mcp_modules = _count_mcp_modules()

    # hard_rule_4: just the schema version number
    if "hard_rule_4" in sections:
        expected = str(schema_version)
        if sections["hard_rule_4"].strip() != expected:
            errors.append(f"AGENTS.md hard_rule_4: expected {expected}, got {sections['hard_rule_4'].strip()}")

    # hard_rule_6: tool counts in the sentence
    if "hard_rule_6" in sections:
        content = sections["hard_rule_6"]
        m = re.search(r"(\d+) CORE tools", content)
        if m and int(m.group(1)) != tools["core"]:
            errors.append(f"AGENTS.md hard_rule_6 CORE count: expected {tools['core']}, got {m.group(1)}")
        m = re.search(r"(\d+) ADMIN", content)
        if m and int(m.group(1)) != tools["admin"]:
            errors.append(f"AGENTS.md hard_rule_6 ADMIN count: expected {tools['admin']}, got {m.group(1)}")
        m = re.search(r"(\d+) DEPRECATED", content)
        if m and int(m.group(1)) != tools["deprecated"]:
            errors.append(f"AGENTS.md hard_rule_6 DEPRECATED count: expected {tools['deprecated']}, got {m.group(1)}")

    # what_this_system_is: surface line
    if "what_this_system_is" in sections:
        content = sections["what_this_system_is"]
        m = re.search(r"(\d+) CORE verbs", content)
        if m and int(m.group(1)) != tools["core"]:
            errors.append(f"AGENTS.md what_this_system_is CORE count: expected {tools['core']}, got {m.group(1)}")
        m = re.search(r"v(\d+)", content)
        if m and int(m.group(1)) != schema_version:
            errors.append(f"AGENTS.md what_this_system_is schema version: expected v{schema_version}, got v{m.group(1)}")

    # current_state: schema version, migration count, test counts
    if "current_state" in sections:
        content = sections["current_state"]
        m = re.search(r"Schema v(\d+)", content)
        if m and int(m.group(1)) != schema_version:
            errors.append(f"AGENTS.md current_state schema version: expected v{schema_version}, got v{m.group(1)}")
        m = re.search(r"(\d+) migrations", content)
        if m and int(m.group(1)) != migrations:
            errors.append(f"AGENTS.md current_state migration count: expected {migrations}, got {m.group(1)}")
        m = re.search(r"(\d+) test files", content)
        if m and int(m.group(1)) != test_files:
            errors.append(f"AGENTS.md current_state test file count: expected {test_files}, got {m.group(1)}")
        m = re.search(r"(\d+)\+ test functions", content)
        if m and int(m.group(1)) != test_funcs:
            errors.append(f"AGENTS.md current_state test function count: expected {test_funcs}, got {m.group(1)}")

    # critical_path: hook count, cron count, mcp modules, test files/functions
    if "critical_path" in sections:
        content = sections["critical_path"]
        m = re.search(r"(\d+) lifecycle hooks", content)
        if m and int(m.group(1)) != hooks:
            errors.append(f"AGENTS.md critical_path hook count: expected {hooks}, got {m.group(1)}")
        m = re.search(r"(\d+)\+ scheduled jobs", content)
        if m and int(m.group(1)) != cron:
            errors.append(f"AGENTS.md critical_path cron count: expected {cron}, got {m.group(1)}")
        m = re.search(r"\((\d+) modules\)", content)
        if m and int(m.group(1)) != mcp_modules:
            errors.append(f"AGENTS.md critical_path MCP module count: expected {mcp_modules}, got {m.group(1)}")

    return errors


# ---------------------------------------------------------------------------
# Check 3: MCP_SURFACE.md tool counts
# ---------------------------------------------------------------------------


def check_mcp_surface_md() -> list[str]:
    errors: list[str] = []
    surface_md = REPO / "docs" / "MCP_SURFACE.md"
    if not surface_md.exists():
        errors.append("docs/MCP_SURFACE.md not found")
        return errors

    text = surface_md.read_text(encoding="utf-8")
    tools = _parse_tool_registry()
    schema_version = _parse_schema_version()
    migrations = _count_migrations()

    # Check "17 CORE verbs" line
    m = re.search(r"(\d+) CORE verbs", text)
    if m and int(m.group(1)) != tools["core"]:
        errors.append(f"MCP_SURFACE.md CORE count: expected {tools['core']}, got {m.group(1)}")

    # Check "17 CORE tools" line (in CORE Verbs section)
    for m in re.finditer(r"(\d+) CORE tools", text):
        if int(m.group(1)) != tools["core"]:
            errors.append(f"MCP_SURFACE.md CORE tools count: expected {tools['core']}, got {m.group(1)}")
            break

    # Check "87 ADMIN" or "95 ADMIN" in the admin tools section
    m = re.search(r"(\d+) ADMIN \+ (\d+) DEPRECATED", text)
    if m:
        if int(m.group(1)) != tools["admin"]:
            errors.append(f"MCP_SURFACE.md ADMIN count: expected {tools['admin']}, got {m.group(1)}")
        if int(m.group(2)) != tools["deprecated"]:
            errors.append(f"MCP_SURFACE.md DEPRECATED count: expected {tools['deprecated']}, got {m.group(2)}")

    # Check schema version in header
    m = re.search(r"Schema v(\d+)", text)
    if m and int(m.group(1)) != schema_version:
        errors.append(f"MCP_SURFACE.md schema version: expected v{schema_version}, got v{m.group(1)}")

    # Check migration count in schema section
    m = re.search(r"(\d+) migrations", text)
    if m and int(m.group(1)) != migrations:
        errors.append(f"MCP_SURFACE.md migration count: expected {migrations}, got {m.group(1)}")

    return errors


# ---------------------------------------------------------------------------
# Fix: regenerate MCP_SURFACE.md AUTO-GEN spans from live code
# ---------------------------------------------------------------------------


def regenerate_mcp_surface_md() -> list[str]:
    """Rewrite the AUTO-GEN marked spans in docs/MCP_SURFACE.md.

    Keeps MCP_SURFACE.md's hand-authored reference content but auto-syncs
    the schema-version / migration-count lines so a SCHEMA_VERSION bump no
    longer requires a manual edit (and the doc-drift test stops failing on
    schema bumps).  Returns a list of error strings (empty on success).
    """
    errors: list[str] = []
    surface_md = REPO / "docs" / "MCP_SURFACE.md"
    if not surface_md.exists():
        return ["docs/MCP_SURFACE.md not found"]

    schema_version = _parse_schema_version()
    migrations = _count_migrations()
    text = surface_md.read_text(encoding="utf-8")

    header_span = (
        f"<!--AUTO-GEN:START key=\"mcp_surface_schema_header\"-->\n"
        f"> Last updated: 2026-07-27. Schema v{schema_version}. Multi-tenant isolation enforced.\n"
        f"<!--AUTO-GEN:END key=\"mcp_surface_schema_header\"-->"
    )
    version_span = (
        f"<!--AUTO-GEN:START key=\"mcp_surface_schema_version\"-->\n"
        f"Current: **v{schema_version}** ({migrations} migrations, 100% down-migration coverage)\n"
        f"<!--AUTO-GEN:END key=\"mcp_surface_schema_version\"-->"
    )

    new_text = _replace_auto_gen(text, "mcp_surface_schema_header", header_span)
    new_text = _replace_auto_gen(new_text, "mcp_surface_schema_version", version_span)

    if new_text != text:
        surface_md.write_text(new_text, encoding="utf-8")
    return errors


def _replace_auto_gen(text: str, key: str, replacement: str) -> str:
    """Replace the content between AUTO-GEN markers for *key* with *replacement*."""
    pattern = re.compile(
        r"<!--AUTO-GEN:START key=\"" + re.escape(key) + r"\"-->\n"
        r".*?\n"
        r"<!--AUTO-GEN:END key=\"" + re.escape(key) + r"\"-->",
        re.DOTALL,
    )
    if not pattern.search(text):
        return text
    return pattern.sub(replacement, text, count=1)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    all_errors: list[str] = []

    import argparse

    parser = argparse.ArgumentParser(description="Documentation drift checker")
    parser.add_argument(
        "--fix",
        action="store_true",
        help="Regenerate AUTO-GEN spans (e.g. MCP_SURFACE.md schema version) before checking",
    )
    args = parser.parse_args()

    if args.fix:
        fix_errors = regenerate_mcp_surface_md()
        for e in fix_errors:
            print(f"[FIX-ERR] {e}")

    print("=== doc_drift_check ===")

    checks = [
        ("architecture.md", check_architecture_md),
        ("AGENTS.md", check_agents_md),
        ("MCP_SURFACE.md", check_mcp_surface_md),
    ]

    for label, fn in checks:
        errors = fn()
        if errors:
            print(f"\n[DRIFT] {label}:")
            for e in errors:
                print(f"  - {e}")
            all_errors.extend(errors)
        else:
            print(f"[OK]    {label}")

    if all_errors:
        print(f"\n{len(all_errors)} drift issue(s) found. Fix then re-run.")
        return 1

    print("\nAll docs in sync with live code.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
